### ISSUE TITLE
Can't compile minimal example

### ISSUE THREAD

**Issue by Mr-Andersen** [MarcelineVQ/idris2-curl#2]
I use `Idris 2, version 0.2.1-a9ff13c66`, `git clone`'d your lib, ran `make install`. Compiler reported error:
```
1/22: Building Derive.Common (src/Derive/Common.idr)
Error: mapName is not covering.

src/Derive/Common.idr:33:1--35:8
 33 | export
 34 | mapName : (String -> String) -> Name -> Name
 35 | mapName f (UN x) = UN (f x)

Missing cases:
    mapName _ (RF _)

Error: nameStr is not covering.

src/Derive/Common.idr:26:1--28:8
 26 | export
 27 | nameStr : Name -> String
 28 | nameStr (UN x) = x

Missing cases:
    nameStr (RF _)
```
So I added missing cases (maybe wrong way):
```
diff --git a/src/Derive/Common.idr b/src/Derive/Common.idr
index 77d4604..6060d1e 100644
--- a/src/Derive/Common.idr
+++ b/src/Derive/Common.idr
@@ -29,6 +29,7 @@ nameStr (UN x) = x
 nameStr (MN x y) = x
 nameStr (NS xs x) = nameStr x
 nameStr (DN x y) = x
+nameStr (RF x) = x

 export
 mapName : (String -> String) -> Name -> Name
@@ -36,6 +37,7 @@ mapName f (UN x) = UN (f x)
 mapName f (MN x y) = MN (f x) y
 mapName f (NS x y) = NS x (mapName f y)
 mapName f (DN x y) = DN (f x) y
+mapName f (RF x) = RF (f x)

 export
 lookupType : Name -> Elab (Name, TTImp)
```
Now the library compiles successfully, but when compiling the following code with `idris2 -p curl Main.idr -o Main.exe`...
```
module Main

import Network.Curl.Easy

main : IO ()
main = do
    CURLE_OK <- curl_global_init | c => do
        putStrLn $ "error in curl_global_init: " ++ show c

    Just cli <- curlEasyInit | Nothing => putStrLn "error in curlEasyInit"

    CURLE_OK <- curlEasySetopt cli CURLOPT_URL "https://google.com" | c => do
        putStrLn $ "error in curlEasySetopt: " ++ show c

    curlEasyCleanup cli
    curl_global_cleanup
```
... I get this error:
```
Error: Can't pass argument of type Builtin.Void  to foreign function
```
Maybe, I've made a mistake in the code?

**Comment by MarcelineVQ** [comment]
The Name problem was just due to being out of date with idris2's development.
You've not done anything wrong that I can see in your code. I was trying to use Void as a placeholder to prevent users from using unimplemented things but it's resulted in the error you see. I'll change that now since it's not truly that important.

**Comment by Mr-Andersen** [comment]
Quite sad that the compiler doesn't show which expression exactly evaluates to Void. Made it hard for me to trace the root of problem.

**Comment by Mr-Andersen** [comment]
Yay, it works! I could make a couple of examples and make a PR. Do you need them?

**Comment by ulidtko** [comment]
Accepting a PR is 1 click, even easier than replying — just do it :wink:

**Comment by MarcelineVQ** [comment]
@Mr-Andersen absolutely!
